apiVersion: v1
kind: ServiceAccount
metadata:
  name: porter-workflow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: porter-workflow-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: workflow-role
subjects:
  - kind: ServiceAccount
    name: porter-workflow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-role
rules:
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - get
      - watch
      - patch
      - list
      - delete
      - create
  - apiGroups:
      - ''
    resources:
      - persistentvolumeclaims
    verbs:
      - get
      - watch
      - patch
      - list
      - delete
      - create
  - apiGroups:
      - ''
    resources:
      - namespaces
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - get
      - list
  - apiGroups:
      - ''
    resources:
      - pods/log
    verbs:
      - get
      - watch
  - apiGroups:
      - ''
    resources:
      - pods/exec
    verbs:
      - create
  - apiGroups:
      - ''
    resources:
      - configmaps
    verbs:
      - create
      - get
      - update
  - apiGroups:
      - 'batch'
    resources:
      - jobs
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete

  - apiGroups:
      - argoproj.io
    resources:
      - workflows
    verbs:
      - create
      - get
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtasksets
      - workflowtasksets/finalizers
      - workflowtaskresults
      - workflowtaskresults/finalizers
    verbs:
      - list
      - create
      - watch
      - get
      - update
      - patch

  - apiGroups:
      - getporter.org
    resources:
      - installations
      - agentactions
    verbs:
      - list
      - watch
      - get
      - update
      - patch
      - create
      - delete
