# Source: mongodb/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: porter-operator-mongodb
  namespace: porter-operator-system
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/instance: porter-operator
    app.kubernetes.io/component: mongodb
type: Opaque
data:
  mongodb-root-password: 'cG9ydGVyLWFyZ28tZGVtbwo='
