apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - operator.yaml
  - namespace

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: manager
    newName: ghcr.io/getporter/porter-operator-manager
    newTag: v0.8.2-28-g37ed573
