apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - operator.yaml
  - namespace

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: manager
    newName: ghcr.io/troy0820/porter-operator
    newTag: v1.0.0
