apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    cert-manager.io/inject-ca-from: otel/opentelemetry-operator-serving-cert
  name: opentelemetrycollectors.opentelemetry.io
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: otel/opentelemetry-operator-serving-cert
  name: opentelemetry-operator-mutating-webhook-configuration
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: otel/opentelemetry-operator-serving-cert
  name: opentelemetry-operator-validating-webhook-configuration
