apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/name: opentelemetry-operator
  name: opentelemetry-operator-serving-cert
  namespace: otel
spec:
  dnsNames:
    - opentelemetry-operator-webhook-service.otel.svc
    - opentelemetry-operator-webhook-service.otel.svc.cluster.local
