apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: otel
resources:
  - ../../base
  - configs/otel-collector-config.yaml

patchesStrategicMerge:
  - certificate.yaml
  - annotations.yaml
