apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    cert-manager.io/inject-ca-from: otel/jaeger-operator-serving-cert
  name: jaegers.jaegertracing.io
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: otel/jaeger-operator-serving-cert
  name: jaeger-operator-mutating-webhook-configuration
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: otel/jaeger-operator-serving-cert
  name: jaeger-operator-validating-webhook-configuration
