apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    name: jaeger-operator
  name: jaeger-operator-serving-cert
  namespace: otel
spec:
  dnsNames:
    - jaeger-operator-webhook-service.otel.svc
    - jaeger-operator-webhook-service.otel.svc.cluster.local
