---
apiVersion: jaegertracing.io/v1
kind: 'Jaeger'
metadata:
  name: porter
spec:
  strategy: allInOne
  allInOne:
    image: jaegertracing/all-in-one:1
    options:
      log-level: debug
      query:
        base-path: /tracing
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - porter-argo.localtest.me
  ui:
    options:
      dependencies:
        menuEnabled: false
      tracking:
        gaID: UA-000000-2
      menu:
        - label: 'About Jaeger'
          items:
            - label: 'Documentation'
              url: 'https://www.jaegertracing.io/docs/latest'
  storage:
    options:
      memory:
        max-traces: 100000
