apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
resources:
  - porter-grpc-deployment.yaml
  - porter-grpc-service.yaml
configMapGenerator:
  - name: porter-grpc-service-config
    files:
      - config=configs/porter-grpc-service-config.yaml
