apiVersion: v1
kind: Service
metadata:
  labels:
    app: porter-grpc-service
  name: porter-grpc-service
spec:
  ports:
    - port: 3001
      protocol: TCP
      targetPort: 3001
  selector:
    app: porter-grpc-service
  type: ClusterIP
