apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../quick-start/postgres
  - ingress.yaml

patches:
  - target:
      kind: Deployment
      name: argo-server
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/env
        value:
        - name: BASE_HREF
          value: "/"
